# Generated by Django 2.2.14 on 2020-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0007_auto_20170316_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='state',
            field=models.CharField(choices=[('nc', 'North Carolina')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statefacts',
            name='state_key',
            field=models.CharField(choices=[('nc', 'North Carolina')], max_length=2, unique=True),
        ),
    ]
