# Generated by Django 3.2.14 on 2023-03-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0008_auto_20200806_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusprofile',
            name='geography',
            field=models.CharField(choices=[('county', 'County'), ('place', 'Place'), ('state', 'State')], max_length=16),
        ),
    ]
