# Generated by Django 3.2.25 on 2025-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsdata', '0009_alter_censusprofile_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusprofile',
            name='year',
            field=models.PositiveSmallIntegerField(default=2018),
        ),
    ]
