# Generated by Django 3.2.25 on 2025-05-19 18:41

from django.db import migrations, models


def just_delete_everything(apps, schema_editor):
    CensusProfile = apps.get_model("tsdata", "CensusProfile")
    CensusProfile.objects.all().delete()


def reverse_move_census_profile_id(apps, schema_editor):
    # This is a no-op since we can't reverse the operation without knowing the original IDs.
    # In practice, this should be handled with a data migration that restores the original IDs.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tsdata", "0010_censusprofile_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusprofile",
            name="acs_id",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.RunPython(just_delete_everything, reverse_move_census_profile_id),
        migrations.AlterField(
            model_name="censusprofile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
