language: python

sudo: false

python:
  - "3.7"

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

cache:
  directories:
    - $HOME/.cache/pip

env:
  - DJANGO_SETTINGS_MODULE="traffic_stops.settings.dev" PGHOST="127.0.0.1" PGPORT="5432" PGUSER="postgres"

# install:
#   - pip install -U pip
#   - pip install -U -r requirements/dev/dev.txt
#   - nvm install 6.12.0
#   - nvm use 6.12.0
#   - npm install

before_script:
  - createdb -E UTF-8 traffic_stops -U $PGUSER -h $PGHOST -p $PGPORT
  - createdb -E UTF-8 traffic_stops_nc -U $PGUSER -h $PGHOST -p $PGPORT

script:
  - coverage run manage.py test
  - coverage report -m --fail-under 74
  - flake8 .
  - npm test
  - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
