version: '3.4'

services:
  app:
    environment:
      DJANGO_SETTINGS_MODULE: traffic_stops.settings.deploy
      DATABASE_URL: postgres://postgres@db:5432/traffic_stops
      DATABASE_URL_NC: postgres://postgres@db:5432/traffic_stops_nc
      DATABASE_URL_MD: postgres://postgres@db:5432/traffic_stops_md
      DATABASE_URL_IL: postgres://postgres@db:5432/traffic_stops_il
      CACHE_HOST: cache:11211
      ENVIRONMENT: local
      DJANGO_SECRET_KEY: insecure-dev-key
      DJANGO_MANAGEPY_MIGRATE: "on"
      DOMAIN: localhost
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      SESSION_COOKIE_SECURE: "False"
    build:
      context: .
      dockerfile: ./Dockerfile
      # target: deploy
    command: ["uwsgi", "--show-config"]
    links:
      - db:db
    ports:
      - "8000:8000"
  # cache:
  #   image: memcached:1.6-alpine
  # mailhog:
  #   image: mailhog/mailhog:v1.0.0
