version: '3.4'

services:
  app:
    image: trafficstops_app:latest
    command: ["uwsgi", "--show-config"]
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
    env_file:
      - .docker.env
    links:
      - db:db
    depends_on:
      - redis
      - mailhog
    ports:
      - "8000:8000"
  worker:
    image: trafficstops_app:latest
    command: ["celery", "--app=traffic_stops", "worker", "-l", "info"]
    env_file:
      - .docker.env
    links:
      - db:db
    depends_on:
      - app
      - redis
      - mailhog
  beat:
    image: trafficstops_app:latest
    command: ["celery", "--app=traffic_stops", "beat", "--pidfile=/tmp/celerybeat.pid", "--schedule=/tmp/celerybeat-schedule", "-l", "info"]
    env_file:
      - .docker.env
    links:
      - db:db
    depends_on:
      - app
      - redis
      - mailhog
  mailhog:
    image: mailhog/mailhog:v1.0.0
