version: '3.4'

services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: traffic_stops
      DATABASE_URL: postgres://postgres@127.0.0.1:5432/traffic_stops
    image: postgres:12-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint.postgres.sql:/docker-entrypoint-initdb.d/init.sql
    shm_size: 128mb

volumes:
  pgdata:
