version: '3.4'

services:
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: traffic_stops
      DATABASE_URL: postgres://postgres@127.0.0.1:5432/traffic_stops
    image: postgres:12-alpine
    ports:
      - "54344:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint.postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 512mb
  redis:
    image: redis:5-alpine
    ports:
      - "63791:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
