---
# CI Workflow for the Forward Justice/Traffic Stops application

version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
              - v9-pip-dependencies-{{ checksum "requirements/test/test.txt" }}-{{ checksum "requirements/base/base.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v9-pip-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - "env"
          key: v9-pip-dependencies-{{ checksum "requirements/test/test.txt" }}-{{ checksum "requirements/base/base.txt" }}
orbs:
  slack: circleci/slack@3.4.2

jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DJANGO_SETTINGS_MODULE: traffic_stops.settings.test
      DATABASE_URL: postgres://127.0.0.1:54344/traffic_stops
      DATABASE_URL_NC: postgres://127.0.0.1:54344/traffic_stops_nc
      PGHOST: 127.0.0.1
      PGPORT: "54344"
      PGUSER: postgres 
    working_directory: ~/traffic-stops
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            
            python -m pip install pip-tools
            pip-sync requirements/base/base.txt requirements/test/test.txt
      - save_cache_cmd
      - run:
          name: Run Pre-commit
          command: |
            . env/bin/activate

            pre-commit run --all
      - run:
          name: Docker up
          command: |
            docker-compose up -d
      - run:
          name: Test
          command: |
            . env/bin/activate
            pytest
      - slack/status:
          success_message: ":caktus: ${CIRCLE_BRANCH} tests passed. <${CIRCLE_BUILD_URL}|Build> :successful:"
          failure_message: ":sadcactus: ${CIRCLE_BRANCH} tests failed. <${CIRCLE_BUILD_URL}|Build> :failed:"
          include_project_field: false
          include_job_number_field: false
          include_visit_job_action: false

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
