---
# CI/CD Workflow for the learningpower project.
# Builds, tests and deploys the current branch to an EKS cluster.
# This CI/CD configuration depends on some environment variables being set at the project level:
#
# ANSIBLE_VAULT_PASS: Allows ansible to decrypt secrets during the deploy job
# AWS_ACCESS_KEY_ID: Provides key to the aws-cli orb
# AWS_SECRET_ACCESS_KEY: Provides key to the aws-cli orb
# AWS_DEFAULT_REGION: us-east-2

version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
              - v7-pip-dependencies-{{ checksum "requirements/dev/dev.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v7-pip-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - "env"
          key: v7-pip-dependencies-{{ checksum "requirements/dev/dev.txt" }}

jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DATABASE_URL: postgres://127.0.0.1/traffic_stops
      DATABASE_URL_NC: postgres://127.0.0.1/traffic_stops_nc
    working_directory: ~/traffic-stops
    steps:
      - checkout
      - restore_cache_cmd
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate

            pip install -r requirements/test/test.txt
      - save_cache_cmd
      - run:
          name: Docker up
          command: |
            docker-compose up -d
      - run:
          name: Test
          command: |
            . env/bin/activate
            ./manage.py test

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
