---
# CI/CD Workflow for the learningpower project.
# Builds, tests and deploys the current branch to an EKS cluster.
# This CI/CD configuration depends on some environment variables being set at the project level:
#
# ANSIBLE_VAULT_PASS: Allows ansible to decrypt secrets during the deploy job
# AWS_ACCESS_KEY_ID: Provides key to the aws-cli orb
# AWS_SECRET_ACCESS_KEY: Provides key to the aws-cli orb
# AWS_DEFAULT_REGION: us-east-2

version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
              - v6-pip-dependencies-{{ checksum "requirements/dev/dev.txt" }}
              # fallback to using the latest cache if no exact match is found
              - v6-pip-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - "env"
          key: v6-pip-dependencies-{{ checksum "requirements/dev/dev.txt" }}

jobs:
  test:
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgres://127.0.0.1/traffic_stops
          DATABASE_URL_NC: postgres://127.0.0.1/traffic_stops_nc
      - image: postgres:12-alpine
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
    working_directory: ~/traffic-stops
    steps:
      - checkout
      - restore_cache_cmd
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-12
      - run:
          name: Postgres setup
          command: |
            createdb -d DATABASE_URL traffic_stops_nc

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
