- name: caktus hosting services
  hosts: production
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  gather_facts: false
  roles:
    - role: caktus.k8s-hosting-services
  tasks:
    - import_role:
        name: caktus.k8s-hosting-services
        tasks_from: monitoring
