---
# ----------------------------------------------------------------------------
# Global: CloudFormation stack outputs. See all.yml for stack parameters.
# ----------------------------------------------------------------------------

# The connection endpoint for the EKS cluster API
ClusterEndpoint: "https://08D66B4141A37A403A73159D7A66BD66.gr7.us-east-2.eks.amazonaws.com"
# The connection endpoint for the database
DatabaseAddress: "td78e29qmbrmgb.cje1ewiwbprp.us-east-2.rds.amazonaws.com"
# The docker repository URL
RepositoryURL: "606178775542.dkr.ecr.us-east-2.amazonaws.com"

# ----------------------------------------------------------------------------
# caktus.django-k8s: Shared configuration variables for staging and production
#                    environments.
# ----------------------------------------------------------------------------

k8s_auth_host: "{{ ClusterEndpoint }}"
k8s_auth_ssl_ca_cert: "k8s_auth_ssl_ca_cert.txt"
k8s_namespace: "{{ app_name }}-{{ env_name }}"

k8s_ingress_certificate_issuer: letsencrypt-production

# App pod configuration:
k8s_container_name: app
k8s_container_port: 8000
k8s_container_image: "{{ RepositoryURL }}/traff-appli-gvyudgfsjhrz"
k8s_container_image_pull_policy: Always
k8s_container_replicas: 2
k8s_container_resources:
  requests:
    memory: 256Mi
    cpu: 50m
  limits:
    cpu: 250m
k8s_migrations_enabled: true
k8s_migration_command:
  - bash
  - migrate_all_dbs.sh
k8s_collectstatic_enabled: false

# Auxillary pod configuration:
k8s_worker_enabled: true
k8s_worker_replicas: 1
k8s_worker_celery_app: "traffic_stops"
k8s_worker_command:
  - newrelic-admin
  - run-program
  - celery
  - --app={{ k8s_worker_celery_app }}
  - --workdir=/code
  - worker
  - --loglevel=info
k8s_worker_beat_enabled: true
k8s_memcached_enabled: false
k8s_redis_enabled: true

# Shared environment variables:
env_django_debug: false
env_database_url: "postgres://{{ app_name }}_{{ env_name }}:{{ database_password }}@{{ DatabaseAddress }}:5432/{{ app_name }}_{{ env_name }}"
env_database_url_nc: "postgres://{{ app_name }}_{{ env_name }}:{{ database_password }}@{{ DatabaseAddress }}:5432/{{ app_name }}_{{ env_name }}_nc"
env_django_settings: "traffic_stops.settings.deploy"
env_broker_url: redis://redis:6379/0
env_cache_host: redis://redis:6379/1
env_default_file_storage: "{{ app_name }}.storages.MediaBoto3Storage"
env_media_storage_bucket_name: "{{ app_name }}-{{ env_name }}-assets"
env_aws_default_acl: public-read
env_media_location: media/
# New Relic Account: forwardjustice-team@caktusgroup.com
env_new_relic_app_name: "{{ k8s_namespace }}"
env_new_relic_license_key: "{{ k8s_newrelic_license_key }}"
env_sentry_dsn: https://8567ec420cf04ce3b7f4b82d5fff70f7@o168020.ingest.sentry.io/5398612
env_sentry_traces_sample_rate: "1.0"
env_nc_ftp_host: 199.90.195.21
env_nc_ftp_user: TSTOPSuser
env_nc_ftp_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31303932313465363533343935393131393131633266393766643631643932353662386362313064
  3631356231663564343430623530353962356533396261390a613932363166613032386536663032
  65373665363566646265616261623837633132633266363534663166343765313765363638616563
  6562386431376565620a393565363638643332386264663861383761653339666339303666303334
  3532
# *** Email
# 'ses-smtp-user.20200921-084510' user in traffic-stops account
env_email_host: "email-smtp.us-east-2.amazonaws.com"
env_email_host_user: AKIAY2IYSCH3F77YGKIU
env_email_host_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63326431353232626532633236353639383565613539366562383562333632316462303935646461
  3361623338333438343664633962303732613665376266360a656262373730393131643637336537
  33653535616137633632396364386638663539663433333931336663666637333933353965383963
  3861306138336265330a616263353832636239396565306138376332306534666166386539623265
  31326137623163613135346565346632623661303839653038333866363565623865363766326465
  3232353563333332396133636565626662366332356638303166
env_email_use_tls: "true"

k8s_environment_variables:
  CONTAINER_IMAGE_TAG: "{{ k8s_container_image_tag }}"
  DJANGO_DEBUG: "{{ env_django_debug | string | title | string }}"
  DATABASE_URL: "{{ env_database_url }}"
  DATABASE_URL_NC: "{{ env_database_url_nc }}"
  DJANGO_SETTINGS_MODULE: "{{ env_django_settings }}"
  # DOMAIN is the ALLOWED_HOST
  DOMAIN: "{{ k8s_domain_names[0] }}"
  ALLOWED_HOSTS: "{{ k8s_domain_names[0] }}"
  ENVIRONMENT: "{{ env_name }}"
  CACHE_HOST: "{{ env_cache_host }}"
  BROKER_URL: "{{ env_broker_url }}"
  # *** Uploaded media
  DEFAULT_FILE_STORAGE: "{{ env_default_file_storage }}"
  MEDIA_STORAGE_BUCKET_NAME: "{{ env_media_storage_bucket_name }}"
  AWS_DEFAULT_ACL: "{{ env_aws_default_acl }}"
  AWS_DEFAULT_REGION: "{{ aws_region }}"
  MEDIA_LOCATION: "{{ env_media_location }}"
  # *** Email
  # 'ses-smtp-user.20200921-084510' user in traffic-stops account
  EMAIL_HOST: "{{ env_email_host }}"
  EMAIL_HOST_USER: "{{ env_email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ env_email_host_password }}"
  EMAIL_USE_TLS: "{{ env_email_use_tls }}"
  # *** New Relic APM
  NEW_RELIC_APP_NAME: "{{ env_new_relic_app_name }}"
  NEW_RELIC_LICENSE_KEY: "{{ env_new_relic_license_key }}"
  SENTRY_DSN: "{{ env_sentry_dsn }}"
  SENTRY_TRACES_SAMPLE_RATE: "{{ env_sentry_traces_sample_rate }}"
  DJANGO_SECRET_KEY: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35313432353232386662373534636239333765663936643639363266323337333936656462373962
    3766616464653266613234303331663934386462313238370a646532663834356266333765623763
    63633165383834303864613362623364653165623135323138346234313031393461653033306233
    3861323666306530640a346233653332356235623036653865383235626636623764613038653331
    61343666356364623132323230626430616261313463366462643632346132313331316561633764
    37646461333661316261363930626239643633323333633930636232616231326530656233396164
    613035323630616135653866373062303966
  # ** FTP_ACCESS
  NC_FTP_HOST: "{{ env_nc_ftp_host }}"
  NC_FTP_USER: "{{ env_nc_ftp_user }}"
  NC_FTP_PASSWORD: "{{ env_nc_ftp_password }}"
  # Contact form
  CONTACT_US_EMAILS: "{{ env_contact_us_emails|join(':') }}"

# S3 bucket configuration:
k8s_s3_region: "{{ aws_region }}"
k8s_s3_cluster_name: "{{ k8s_cluster_name }}"
