# Generated by Django 3.2.14 on 2022-08-10 19:19

from django.db import migrations


def create_north_carolina_agency(apps, schema_editor):
    Agency = apps.get_model("nc", "Agency")
    Agency.objects.create(id=-1, name="North Carolina State")

class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0005_stopsummary'),
    ]

    operations = [
        migrations.RunPython(create_north_carolina_agency, reverse_code=migrations.RunPython.noop),
    ]
