# Generated by Django 3.2.14 on 2023-02-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0006_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.CharField(blank=True, choices=[('copwatch-new-policy', 'New Policy'), ('forward-justice-logo', 'Forward Justice Logo')], max_length=200, null=True),
        ),
    ]
