# Generated by Django 3.2.14 on 2023-02-28 16:21

import django.utils.timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0007_alter_resource_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='agency',
        ),
        migrations.AddField(
            model_name='resource',
            name='agencies',
            field=models.ManyToManyField(related_name='resources', to='nc.Agency'),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
