# Generated by Django 3.2.14 on 2023-03-21 20:33

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0009_resource_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nc.resource')),
            ],
        ),
    ]
