# Generated by Django 3.2.14 on 2023-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0010_resourcefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.CharField(blank=True, choices=[('copwatch-new-policy', 'New Policy'), ('forward-justice-logo', 'Forward Justice Logo'), ('copwatch-white-paper', 'White Paper')], max_length=200, null=True),
        ),
    ]
