# Generated by Django 3.2.14 on 2023-11-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0011_alter_resource_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrabandSummary',
            fields=[
                ('id', models.PositiveIntegerField(db_column='contraband_type_id', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('officer_id', models.CharField(max_length=15)),
                ('stop_purpose_group', models.CharField(choices=[('Safety Violation', 'Safety Violation'), ('Regulatory and Equipment', 'Regulatory Equipment'), ('Other', 'Other')], max_length=32)),
                ('driver_race_comb', models.CharField(choices=[('A', 'Asian'), ('B', 'Black'), ('H', 'Hispanic'), ('I', 'Native American'), ('U', 'Other'), ('W', 'White')], max_length=2)),
                ('driver_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=8)),
                ('driver_searched', models.BooleanField()),
                ('contraband_found', models.BooleanField()),
                ('contraband_type', models.CharField(max_length=16)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
