# Generated by Django 3.2.25 on 2025-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0012_contrabandsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCCensusProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acs_id', models.CharField(max_length=32, verbose_name='ACS ID')),
                ('location', models.CharField(max_length=64)),
                ('geography', models.CharField(choices=[('state', 'State'), ('county', 'County'), ('place', 'Place')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('race', models.CharField(max_length=32)),
                ('population', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'NC Census Profile',
                'verbose_name_plural': 'NC Census Profiles',
            },
        ),
    ]
