# Generated by Django 3.2.25 on 2025-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nc", "0013_nccensusprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikelihoodStopSummary",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "driver_race_comb",
                    models.CharField(
                        choices=[
                            ("Asian", "Asian"),
                            ("Black", "Black"),
                            ("Hispanic", "Hispanic"),
                            ("Native American", "Native American"),
                            ("Other", "Other"),
                            ("White", "White"),
                        ],
                        db_column="driver_race",
                        max_length=216,
                        verbose_name="Driver Race",
                    ),
                ),
                ("population", models.PositiveIntegerField()),
                ("population_total", models.PositiveIntegerField()),
                ("population_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stops", models.PositiveIntegerField()),
                ("stops_total", models.PositiveIntegerField()),
                ("stop_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("baseline_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("stop_rate_ratio", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Likelihood of Stop Summary",
                "verbose_name_plural": "Likelihood of Stop Summaries",
                "managed": False,
            },
        ),
    ]
