# Generated by Django 3.2.25 on 2025-04-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0014_auto_20250204_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccensusprofile',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
