# Generated by Django 3.2.25 on 2025-05-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0015_nccensusprofile_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikelihoodStopSummary',
        ),
    ]
