# Generated by Django 5.2.10 on 2026-01-27 20:39

import django_pgviews.db.migrations.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0016_delete_likelihoodstopsummary'),
    ]

    operations = [
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name='ContrabandSummary',
            materialized=True,
            db_name='nc_contrabandsummary',
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name='StopSummary',
            materialized=True,
            db_name='nc_stopsummary',
        ),
    ]
