# Generated by Django 5.2.11 on 2026-02-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0017_auto_20260127_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100)),
                ('census_profile_id', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['county_name'],
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nc.county'),
        ),
    ]
