# Generated by Django 5.2.11 on 2026-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nc', '0018_likelihood_of_stop_summary_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='nccensusprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nccensusprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
