name: test

on:
  pull_request:
  push:
    branches: [main, develop, actions-cd]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        # From:
        # https://docs.github.com/en/actions/guides/creating-postgresql-service-containers
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: traffic_stops
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        volumes:
          - ./docker-entrypoint.postgres.sql:/docker-entrypoint-initdb.d/init.sql
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements/*/*.txt'
      - name: Install dependencies
        run: |
          python -m pip install pip-tools
          pip-sync requirements/base/base.txt requirements/test/test.txt
